apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amy-directory
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source:
    # directory:
      # exclude: 'sub-directory' 
        # include: '{serviceaccount.yml,service.yml}'
      # recurse: true 
    path: v03-argocd-applications/directoryOfmanifests
    repoURL: https://github.com/amydeg25/argocd-tutorial.git
    targetRevision: main

