apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amy-app-rocks # Release name of helm/application!!
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: application-from-helm-amy # Helm Chart Release Name !!
      # valueFiles:
      #   - custom-values.yaml
      # Precedence Order: parameters > Custom Values/valueFiles > values.yaml(Helm Repo)!!
      parameters: 
        - name: "replicaCount"
          value: "2"
          #      valueFiles:
          #        - custom-values.yaml
          #      values: |
          #        replicaCount: 3
          #      valuesObject:
          #        replicaCount: 5
          #      parameters:
          #        - name: "replicaCount"
          #          value: "1"
    path: v03-argocd-applications/helm/nginx
    repoURL: https://github.com/amydeg25/argocd-tutorial.git
    targetRevision: main