apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch # Here release name of app will change!
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: application-from-helm-amy # Here we change the release name of the Chart!
      valueFiles:
        - custom-values.yaml
      # parameters: 
      #   - name: "replicaCount"
      #     value: "2"
          #      valueFiles:
          #        - custom-values.yaml
          #      values: |
          #        replicaCount: 3
          #      valuesObject:
          #        replicaCount: 5
          #      parameters:
          #        - name: "replicaCount"
          #          value: "1"
    path: v03-argocd-applications/helm/nginx
    repoURL: https://github.com/amydeg25/argocd-tutorial.git
    targetRevision: main

